PandoraWeb/Models/Common/DocumentGridViewModel.cs
using System.Collections.Generic;
using PandoraObjects.Common;

namespace PandoraWeb.Models.Common
{
    public class DocumentGridViewModel
    {
        public string Code { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }

        public decimal Amount => Quantity * UnitPrice;
    }
}

PandoraWeb/Controllers/RentalController.cs
using DevExpress.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PandoraWeb.Controllers
{
    public class RentalController : Controller
    {
        // GET: Rental
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Quote()
        {
            return View();
        }
        
    }
}

PandoraWeb/Views/Shared/DocumentTemplate/_DocumentGridView.cshtml
@Html.Action("DocumentGridViewPartial", "Rental")

PandoraWeb/Views/Shared/DocumentTemplate/_DocumentPartialView.cshtml
<div class="panel-heading bg-primary">
    <h3 class="panel-title"> Documento #000123</h3>
</div>

<div class="panel panel-default form-inline">
    <div class="panel-heading container-fluid">

        <div class="row">
            <div class="col-md-9">

                <div class="form-group">
                    <label for="CustomerEdit">Nombre del cliente</label>
                    @Html.DevExpress().ButtonEdit(settings =>
                    {
                        settings.Name = "CustomerEdit";
                        //settings.ControlStyle.CssClass = "form-control";
                        settings.Width = 310;
                        settings.Properties.Buttons.Add(new EditButton());
                        settings.Properties.ClientSideEvents.ButtonClick = "buttonEdit1_ButtonClick";
                    }).GetHtml()

                </div>

                <div class="form-group">
                    <label for="ContactEdit">Persona de Contacto</label>
                    @Html.DevExpress().ButtonEdit(settings =>
                    {
                        settings.Name = "ContactEdit";
                        //settings.ControlStyle.CssClass = "form-control";
                        settings.Width = 200;
                        settings.Properties.Buttons.Add(new EditButton());
                        settings.Properties.ClientSideEvents.ButtonClick = "buttonEdit1_ButtonClick";
                    }).GetHtml()

                </div>

                <div class="form-group">
                    <label for="ProjectEdit">Nombre de proyecto</label>
                    @Html.DevExpress().ButtonEdit(settings =>
                    {
                        settings.Name = "ProjectEdit";
                        settings.Width = 310;
                        settings.Properties.Buttons.Add(new EditButton());
                        settings.Properties.ClientSideEvents.ButtonClick = "buttonEdit1_ButtonClick";
                    }).GetHtml()

                </div>

            </div>

            <div class="col-md-3">
                <p class="text-right no-margin">Saldo Actual</p>
                <h1 class="text-right no-margin"> $ 123.456,00 </h1>
            </div>
        </div>

    </div>


    <div class="panel-body container-fluid">
        <div class="row">
            <div class="col-md-7">
                <div class="form-group">
                    <label for="ReferenceEdit">Referencia</label>
                    @Html.DevExpress().ButtonEdit(settings =>
                    {
                        settings.Name = "RefereceEdit";
                        //settings.ControlStyle.CssClass = "form-control";
                        settings.Width = 120;
                        settings.Properties.NullText = "00012345";
                        settings.Properties.Buttons.Add(new EditButton());
                        settings.Properties.ClientSideEvents.ButtonClick = "buttonEdit1_ButtonClick";
                    }).GetHtml()
                </div>

                <div class="form-group">
                    <label for="CurrencyEdit">Moneda</label>
                    @Html.DevExpress().ComboBox(settings =>
                    {
                        settings.Name = "CurrencyEdit";
                        settings.Properties.Items.Add("Dolares");
                        settings.Properties.Items.Add("Colones");
                        settings.Properties.Items.Add("Euros");
                        settings.Width = 120;
                        settings.SelectedIndex = 2;
                    }).GetHtml()
                </div>

                <div class="form-group">
                    <label for="RateEdit">Tipo Cambio</label>
                    @Html.DevExpress().TextBox(settings =>
                    {
                        settings.Name = "RateEdit";
                        settings.Text = "123456";
                        settings.Properties.DisplayFormatString = "C";
                        settings.ReadOnly = true;
                        settings.Enabled = false;
                        settings.Width = 120;

                    }).GetHtml()
                </div>

                <div class="form-group">
                    <label for="TermsEdit">Moneda</label>
                    @Html.DevExpress().ComboBox(settings =>
                    {
                        settings.Name = "TermsEdit";
                        settings.Properties.Items.Add("Contado");
                        settings.Width = 120;
                        settings.SelectedIndex = 2;
                    }).GetHtml()
                </div>

                <div class="form-group">
                    <label for="DateCustomEdit">Fecha Customisable</label>
                    @Html.DevExpress().DateEdit(settings =>
                    {
                        settings.Name = "DateCustomEdit";
                        settings.Properties.EditFormat = EditFormat.Custom;
                        settings.Date = new DateTime(2009, 11, 2, 9, 23, 0);
                        settings.Width = 120;
                        settings.Properties.TimeSectionProperties.
                            TimeEditProperties.EditFormatString = "hh:mm tt";
                    }).GetHtml()
                </div>
            </div>

            <div class="col-md-5">


                <table class="table table-condensed table-borderless no-margin">

                    <tbody>
                    <tr>
                        <td class="text-right" width="25%"><label>Fecha Documento</label></td>
                        <td class="text-right" width="25%">
                            @Html.DevExpress().DateEdit(settings =>
                       {
                           settings.Name = "DocumentDateEdit";
                           settings.Properties.EditFormat = EditFormat.Custom;
                           settings.Date = DateTime.Today;

                           settings.Width = Unit.Percentage(90);
                           settings.ControlStyle.CssClass = "pull-right";
                           settings.Properties.TimeSectionProperties.TimeEditProperties.EditFormatString = "hh:mm tt";
                       }).GetHtml()
                        </td>
                        <td class="text-right" width="25%"><label>Documento #</label></td>
                        <td class="text-right" width="25%">@Html.DevExpress().ButtonEdit(settings =>
                                          {
                                              settings.Name = "DocumentNumberEdit";
                                              settings.Width = Unit.Percentage(90);
                                              settings.Properties.NullText = "00012345";
                                              settings.ControlStyle.CssClass = "pull-right";
                                              settings.Properties.Buttons.Add(new EditButton());
                                              settings.Properties.ClientSideEvents.ButtonClick = "buttonEdit1_ButtonClick";
                                          }).GetHtml()
                        </td>
                    </tr>
                    <tr> <td class="text-right" width="25%"><label>Fecha Contabilizacion</label></td>
                        <td class="text-right" width="25%">
                            @Html.DevExpress().DateEdit(settings =>
                       {
                           settings.Name = "AccountingDateEdit";
                           settings.Properties.EditFormat = EditFormat.Custom;
                           settings.Date = new DateTime(2009, 11, 2, 9, 23, 0);

                           settings.Width = Unit.Percentage(90);
                           settings.ControlStyle.CssClass = "pull-right";
                           settings.Properties.TimeSectionProperties.
                               TimeEditProperties.EditFormatString = "hh:mm tt";
                       }).GetHtml()
                        </td>
                        <td class="text-right" width="25%"><label>Estado</label></td>
                        <td class="text-right" width="25%">
                            @Html.DevExpress().TextBox(settings =>
                       {
                           settings.Name = "DocumentEstate";
                           settings.Text = "Pendiente";
                           settings.Properties.DisplayFormatString = "C";
                           settings.ControlStyle.CssClass = "pull-right";
                           settings.ReadOnly = true;
                           settings.Enabled = false;
                           settings.Width = Unit.Percentage(90);
                           //settings.ControlStyle.Width = Unit.Percentage(100);

                       }).GetHtml()
                        </td> </tr>
                    </tbody>
                </table>


            </div>
        </div>


    

    </div>

    <div class="panel-heading">
        @Html.DevExpress().PageControl(settings =>
   {
       settings.Name = "DocumentPageControl";
       settings.TabPages.Add("Contenido").SetContent(() =>
       {
           Html.RenderPartial("DocumentTemplate/_DocumentGridView");

       });
       settings.TabPages.Add("Direccion").SetContent(() =>
       {
           ViewContext.Writer.Write("Page content 1");
       });
       settings.TabPages.Add("Notas").SetContent(() =>
       {
           ViewContext.Writer.Write("Page content 2");
       });
   }).GetHtml()
    </div>

    <div class="panel-body container-fluid">
        <div class="row no-gutters">
            <div class="col-md-4">
                <div class="form-group-lg">
                    <label class="text-muted"><small>NOTAS DEL USUARIO</small></label>
                    <textarea rows="4" style="min-width: 100%" class="form-control "></textarea>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="EmployeeEdit">Vendedor</label>
                    @Html.DevExpress().ButtonEdit(settings =>
                {
                    settings.Name = "EmployeeEdit";
                    settings.Width = 200;
                    settings.Properties.Buttons.Add(new EditButton());
                    settings.Properties.ClientSideEvents.ButtonClick = "buttonEdit1_ButtonClick";
                }).GetHtml()

                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="form-group pull-right">
                        @Html.DevExpress().TextBox(settings => { settings.Name = "SubTotalTextBox"; }).GetHtml()
                    </div>
                    <div class="form-group pull-right">
                        <p class="form-control-static">SubTotal &nbsp;</p>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group pull-right">
                        @Html.DevExpress().TextBox(settings =>
                    {
                        settings.Name = "DiscountTextBox";
                        settings.Width = 130;
                        settings.ControlStyle.CssClass = "pull-right";
                    }).GetHtml()

                        @Html.DevExpress().TextBox(settings =>
                    {
                        settings.Name = "DiscountPercentageTextBox";
                        settings.Width = 40;
                        settings.ControlStyle.CssClass = "pull-right";
                    }
                        ).GetHtml()
                    </div>
                    <div class="form-group pull-right">
                        <p class="form-control-static">Descuento &nbsp;</p>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group pull-right">
                        @Html.DevExpress().TextBox(settings =>
                    {
                        settings.Name = "TaxTextBox";
                        settings.Width = 130;
                        settings.ControlStyle.CssClass = "pull-right";
                    }).GetHtml()
                        @Html.DevExpress().TextBox(settings =>
                    {
                        settings.Name = "TaxPercentageTextBox";
                        settings.Width = 40;
                        settings.ControlStyle.CssClass = "pull-right";
                    }
                        ).GetHtml()
                    </div>
                    <div class="form-group pull-right">
                        <p class="form-control-static">Impuesto &nbsp;</p>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group pull-right">
                        @Html.DevExpress().TextBox(settings => { settings.Name = "TotalTextBox"; }).GetHtml()
                    </div>
                    <div class="form-group pull-right">
                        <p class="form-control-static" style="font-weight: 600; font-size: 16px">Total &nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>